services:
  - type: web
    name: magic-card
    runtime: node
    buildCommand: cd frontend && npm install && npm run build && npm install -g serve
    startCommand: serve frontend/dist -s -l $PORT
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
